//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankAccounts = new HashSet<BankAccount>();
        }
    
        public long BankID { get; set; }
        public string Name { get; set; }
        public Nullable<long> BaseInterestRate { get; set; }
        public Nullable<long> InterestTimeInterval { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> PriceTimeInterval { get; set; }
    
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
    }
}
