//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public long AccountID { get; set; }
        public long BankID { get; set; }
        public long CharacterID { get; set; }
        public Nullable<long> InterestTimeInterval { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> PriceTimeInterval { get; set; }
        public Nullable<long> InterestRate { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public float Amount { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual HeroCharacter HeroCharacter { get; set; }
    }
}
