//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterSkill
    {
        public long CharacterID { get; set; }
        public long SkillID { get; set; }
        public Nullable<long> AcquiredManyTimes { get; set; }
        public string TalentID { get; set; }
        public string AdditionalDetails { get; set; }
    
        public virtual HeroCharacter HeroCharacter { get; set; }
        public virtual Talent Talent { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
