//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatapadHacking
    {
        public long DatapadID { get; set; }
        public long HackingCharacterID { get; set; }
        public long AttemptNumber { get; set; }
        public Nullable<bool> Success { get; set; }
        public Nullable<System.DateTime> DateOfAttempt { get; set; }
    
        public virtual Datapad Datapad { get; set; }
        public virtual HeroCharacter HeroCharacter { get; set; }
    }
}
