//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatapadFile
    {
        public long DatapadID { get; set; }
        public long FileNumber { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
        public Nullable<long> EncryptionLevel { get; set; }
    
        public virtual Datapad Datapad { get; set; }
    }
}
