//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datapad
    {
        public Datapad()
        {
            this.DatapadFiles = new HashSet<DatapadFile>();
            this.DatapadHackings = new HashSet<DatapadHacking>();
            this.EventDatapads = new HashSet<EventDatapad>();
        }
    
        public long DatapadID { get; set; }
        public string Content { get; set; }
        public long HackingLevel { get; set; }
        public Nullable<System.Guid> QRCode { get; set; }
    
        public virtual ICollection<DatapadFile> DatapadFiles { get; set; }
        public virtual ICollection<DatapadHacking> DatapadHackings { get; set; }
        public virtual ICollection<EventDatapad> EventDatapads { get; set; }
    }
}
