//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.ElementCompounds = new HashSet<ElementCompound>();
            this.ElementCompounds1 = new HashSet<ElementCompound>();
            this.ElementQRCodes = new HashSet<ElementQRCode>();
            this.EventElements = new HashSet<EventElement>();
        }
    
        public long ElementID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Effect { get; set; }
        public float Price { get; set; }
        public string Picture { get; set; }
        public long AvailabilityID { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public long Discriminator { get; set; }
    
        public virtual ElementAvailability ElementAvailability { get; set; }
        public virtual ICollection<ElementCompound> ElementCompounds { get; set; }
        public virtual ICollection<ElementCompound> ElementCompounds1 { get; set; }
        public virtual ICollection<ElementQRCode> ElementQRCodes { get; set; }
        public virtual ICollection<EventElement> EventElements { get; set; }
        public virtual Item Item { get; set; }
        public virtual Substance Substance { get; set; }
    }
}
