//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDatapad
    {
        public long EventID { get; set; }
        public long DatapadID { get; set; }
        public Nullable<long> NumberOfCopies { get; set; }
    
        public virtual Datapad Datapad { get; set; }
        public virtual Event Event { get; set; }
    }
}
