//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroCharacter
    {
        public HeroCharacter()
        {
            this.AccountHackings = new HashSet<AccountHacking>();
            this.AccountHackings1 = new HashSet<AccountHacking>();
            this.AddressBooks = new HashSet<AddressBook>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.CharacterEventDays = new HashSet<CharacterEventDay>();
            this.CharacterSkills = new HashSet<CharacterSkill>();
            this.CharacterUnlockedSkills = new HashSet<CharacterUnlockedSkill>();
            this.DatapadHackings = new HashSet<DatapadHacking>();
            this.MailInBoxes = new HashSet<MailInBox>();
            this.MailOutBoxes = new HashSet<MailOutBox>();
            this.Messages = new HashSet<Message>();
            this.MessageHackings = new HashSet<MessageHacking>();
            this.NewsHackings = new HashSet<NewsHacking>();
            this.NewsStories = new HashSet<NewsStory>();
            this.SavedMessages = new HashSet<SavedMessage>();
            this.Infections = new HashSet<Infection>();
            this.Talents = new HashSet<Talent>();
        }
    
        public long CharacterID { get; set; }
        public long PlayerID { get; set; }
        public string Name { get; set; }
        public long SpeciesID { get; set; }
        public long Type { get; set; }
        public long ExperiencePoints { get; set; }
        public string Sex { get; set; }
        public long DarkSidePoints { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public string HonorificTitle { get; set; }
        public bool IsAlive { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public string LarpNetworkPassword { get; set; }
        public string BloodFormula { get; set; }
        public Nullable<long> NetworkID { get; set; }
        public Nullable<System.DateTime> LastAccountEncryption { get; set; }
        public long EncryptionLevel { get; set; }
        public Nullable<System.Guid> QRCode { get; set; }
    
        public virtual ICollection<AccountHacking> AccountHackings { get; set; }
        public virtual ICollection<AccountHacking> AccountHackings1 { get; set; }
        public virtual ICollection<AddressBook> AddressBooks { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<CharacterEventDay> CharacterEventDays { get; set; }
        public virtual ICollection<CharacterSkill> CharacterSkills { get; set; }
        public virtual ICollection<CharacterUnlockedSkill> CharacterUnlockedSkills { get; set; }
        public virtual ICollection<DatapadHacking> DatapadHackings { get; set; }
        public virtual Network Network { get; set; }
        public virtual Species Species { get; set; }
        public virtual Player Player { get; set; }
        public virtual ICollection<MailInBox> MailInBoxes { get; set; }
        public virtual ICollection<MailOutBox> MailOutBoxes { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageHacking> MessageHackings { get; set; }
        public virtual ICollection<NewsHacking> NewsHackings { get; set; }
        public virtual ICollection<NewsStory> NewsStories { get; set; }
        public virtual ICollection<SavedMessage> SavedMessages { get; set; }
        public virtual ICollection<Infection> Infections { get; set; }
        public virtual ICollection<Talent> Talents { get; set; }
    }
}
