//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamedata2Entities : DbContext
    {
        public gamedata2Entities()
            : base("name=gamedata2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountHacking> AccountHackings { get; set; }
        public DbSet<AddressBook> AddressBooks { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BankAccount> BankAccounts { get; set; }
        public DbSet<CharacterEventDay> CharacterEventDays { get; set; }
        public DbSet<CharacterSkill> CharacterSkills { get; set; }
        public DbSet<CharacterUnlockedSkill> CharacterUnlockedSkills { get; set; }
        public DbSet<Datapad> Datapads { get; set; }
        public DbSet<DatapadFile> DatapadFiles { get; set; }
        public DbSet<DatapadHacking> DatapadHackings { get; set; }
        public DbSet<DeviceNetwork> DeviceNetworks { get; set; }
        public DbSet<Door> Doors { get; set; }
        public DbSet<Element> Elements { get; set; }
        public DbSet<ElementAvailability> ElementAvailabilities { get; set; }
        public DbSet<ElementCompound> ElementCompounds { get; set; }
        public DbSet<ElementQRCode> ElementQRCodes { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventDatapad> EventDatapads { get; set; }
        public DbSet<EventDay> EventDays { get; set; }
        public DbSet<EventElement> EventElements { get; set; }
        public DbSet<HackingTool> HackingTools { get; set; }
        public DbSet<HeroCharacter> HeroCharacters { get; set; }
        public DbSet<Infection> Infections { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemType> ItemTypes { get; set; }
        public DbSet<MailInBox> MailInBoxes { get; set; }
        public DbSet<MailOutBox> MailOutBoxes { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageHacking> MessageHackings { get; set; }
        public DbSet<Network> Networks { get; set; }
        public DbSet<NewsHacking> NewsHackings { get; set; }
        public DbSet<NewsStory> NewsStories { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<SavedMessage> SavedMessages { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<SkillEffect> SkillEffects { get; set; }
        public DbSet<Species> Species { get; set; }
        public DbSet<Substance> Substances { get; set; }
        public DbSet<SubstanceType> SubstanceTypes { get; set; }
        public DbSet<Talent> Talents { get; set; }
    }
}
