//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MailInBoxes = new HashSet<MailInBox>();
            this.MailOutBoxes = new HashSet<MailOutBox>();
            this.MessageHackings = new HashSet<MessageHacking>();
        }
    
        public long MessageID { get; set; }
        public long SenderCharacter { get; set; }
        public string Subject { get; set; }
        public string Message1 { get; set; }
        public long HackingLevel { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateOfCreation { get; set; }
    
        public virtual HeroCharacter HeroCharacter { get; set; }
        public virtual ICollection<MailInBox> MailInBoxes { get; set; }
        public virtual ICollection<MailOutBox> MailOutBoxes { get; set; }
        public virtual ICollection<MessageHacking> MessageHackings { get; set; }
    }
}
