//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageHacking
    {
        public long MessageID { get; set; }
        public long CharacterID { get; set; }
        public long AttemptNumber { get; set; }
        public bool Success { get; set; }
        public System.DateTime DateOfAttempt { get; set; }
    
        public virtual HeroCharacter HeroCharacter { get; set; }
        public virtual Message Message { get; set; }
    }
}
