//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        public Network()
        {
            this.DeviceNetworks = new HashSet<DeviceNetwork>();
            this.HeroCharacters = new HashSet<HeroCharacter>();
            this.NewsStories = new HashSet<NewsStory>();
            this.Parameters = new HashSet<Parameter>();
        }
    
        public long NetworkID { get; set; }
        public string NetworkName { get; set; }
        public string Description { get; set; }
        public string Faction { get; set; }
    
        public virtual ICollection<DeviceNetwork> DeviceNetworks { get; set; }
        public virtual ICollection<HeroCharacter> HeroCharacters { get; set; }
        public virtual ICollection<NewsStory> NewsStories { get; set; }
        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}
