//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsStory
    {
        public NewsStory()
        {
            this.NewsHackings = new HashSet<NewsHacking>();
        }
    
        public long NewsID { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public long NetworkID { get; set; }
        public Nullable<long> AuthorCharacterID { get; set; }
        public long HackingLevel { get; set; }
    
        public virtual HeroCharacter HeroCharacter { get; set; }
        public virtual Network Network { get; set; }
        public virtual ICollection<NewsHacking> NewsHackings { get; set; }
    }
}
