//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public long NetworkID { get; set; }
        public string Parameter1 { get; set; }
        public string Value { get; set; }
    
        public virtual Network Network { get; set; }
    }
}
