//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.HeroCharacters = new HashSet<HeroCharacter>();
        }
    
        public long PlayerID { get; set; }
        public string MainName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string CountyOrArea { get; set; }
        public string PostCode { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfSubscription { get; set; }
        public string Sex { get; set; }
        public string PlayerCathegory { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<HeroCharacter> HeroCharacters { get; set; }
    }
}
