//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.CharacterSkills = new HashSet<CharacterSkill>();
            this.CharacterUnlockedSkills = new HashSet<CharacterUnlockedSkill>();
            this.SkillEffects = new HashSet<SkillEffect>();
            this.Prerequisites = new HashSet<Skill>();
            this.DependentSkills = new HashSet<Skill>();
            this.Talents = new HashSet<Talent>();
        }
    
        public long SkillID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool AcquireManyTimes { get; set; }
        public long ExperiencePointsCost { get; set; }
        public bool IsAdvanced { get; set; }
    
        public virtual ICollection<CharacterSkill> CharacterSkills { get; set; }
        public virtual ICollection<CharacterUnlockedSkill> CharacterUnlockedSkills { get; set; }
        public virtual ICollection<SkillEffect> SkillEffects { get; set; }
        public virtual ICollection<Skill> Prerequisites { get; set; }
        public virtual ICollection<Skill> DependentSkills { get; set; }
        public virtual ICollection<Talent> Talents { get; set; }
    }
}
