//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent
    {
        public Talent()
        {
            this.CharacterSkills = new HashSet<CharacterSkill>();
            this.CharacterUnlockedSkills = new HashSet<CharacterUnlockedSkill>();
            this.HeroCharacters = new HashSet<HeroCharacter>();
            this.Skills = new HashSet<Skill>();
        }
    
        public string TalentID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long TalentType { get; set; }
    
        public virtual ICollection<CharacterSkill> CharacterSkills { get; set; }
        public virtual ICollection<CharacterUnlockedSkill> CharacterUnlockedSkills { get; set; }
        public virtual ICollection<HeroCharacter> HeroCharacters { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
